### ISSUE TITLE
Read WPA-SEC Crack...

### ISSUE THREAD

**Issue by do-ki** [wpa-2/telegram.py#4]
I have a lot of cracked by WPA-SEC, after pressing the button it displays cracked password however it will stopped and this error show up in logs. Seems there's flood control in place that cause this error. I will check it in Botfather if there's an option to disable it.
```
[2023-07-24 13:59:08,867] [ERROR] No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "/home/pi/plugins/telegram.py", line 29, in <lambda>
    dispatcher.add_handler(CallbackQueryHandler(lambda update, context: self.button_handler(agent, update, context)))
  File "/home/pi/plugins/telegram.py", line 52, in button_handler
    self.read_wpa_sec_cracked(agent, update, context)
  File "/home/pi/plugins/telegram.py", line 110, in read_wpa_sec_cracked
    update.effective_message.reply_text(chunk)
  File "/usr/local/lib/python3.7/dist-packages/telegram/message.py", line 990, in reply_text
    message_thread_id=message_thread_id,
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 544, in send_message
    message_thread_id=message_thread_id,
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/extbot.py", line 213, in _message
    message_thread_id=message_thread_id,
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 344, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 300, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 366, in post
    **urlopen_kwargs,
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 41.0 seconds

```

**Comment by wpa-2** [comment]
Not seen the error my self, how big is the pot file? 
Sorry for late reply.

**Comment by do-ki** [comment]
No worries, 

root@pote:~/handshakes# ls -l *.potfile
-rw-r--r-- 1 root root 122870 Aug 20 03:19 wpa-sec.cracked.potfile

**Comment by wpa-2** [comment]
> No worries,
> 
> root@pote:~/handshakes# ls -l *.potfile -rw-r--r-- 1 root root 122870 Aug 20 03:19 wpa-sec.cracked.potfile

I got something for you to test if you wouldnt mind.
